// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcoHshUWaZ3MxJ6M8X43Zd0RNvI6GGbbM',
    appId: '1:261903952969:web:46bd9298714f8483f2a398',
    messagingSenderId: '261903952969',
    projectId: 'tracky-e4b53',
    authDomain: 'tracky-e4b53.firebaseapp.com',
    storageBucket: 'tracky-e4b53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqU-wUf2j6luTRU4ghVWbFU-o44it8yDA',
    appId: '1:261903952969:android:b863058e085b3e4ef2a398',
    messagingSenderId: '261903952969',
    projectId: 'tracky-e4b53',
    storageBucket: 'tracky-e4b53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_5pg1FrmxZuZMCEJqO9Sy9GZsntABFRc',
    appId: '1:261903952969:ios:e16f9625012162cdf2a398',
    messagingSenderId: '261903952969',
    projectId: 'tracky-e4b53',
    storageBucket: 'tracky-e4b53.appspot.com',
    iosBundleId: 'com.example.tracky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_5pg1FrmxZuZMCEJqO9Sy9GZsntABFRc',
    appId: '1:261903952969:ios:e16f9625012162cdf2a398',
    messagingSenderId: '261903952969',
    projectId: 'tracky-e4b53',
    storageBucket: 'tracky-e4b53.appspot.com',
    iosBundleId: 'com.example.tracky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcoHshUWaZ3MxJ6M8X43Zd0RNvI6GGbbM',
    appId: '1:261903952969:web:5fc053861905955ef2a398',
    messagingSenderId: '261903952969',
    projectId: 'tracky-e4b53',
    authDomain: 'tracky-e4b53.firebaseapp.com',
    storageBucket: 'tracky-e4b53.appspot.com',
  );

}